---

- name: NEWRELIC | Installing dependencies
  apt:
    pkg: apt-transport-https
    state: present

- name: NEWRELIC | Adding APT key
  apt_key:
    id: "{{ repository_key_id }}"
    url: "{{ repository_key_url }}"

- name: NEWRELIC | Add APT repository
  apt_repository:
    repo: "{{ repository_data }}"
    update_cache: yes

- name: NEWRELIC | Installing packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - newrelic-sysmond
