---

- name: NEWRELIC SERVERS AGENT | Checking for key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- name: NEWRELIC SERVERS AGENT | Install
  import_tasks: install.yml
  tags:
    - install

- name: NEWRELIC SERVERS AGENT | Config
  import_tasks: config.yml
  tags:
    - config

- name: NEWRELIC SERVERS AGENT | Service
  import_tasks: service.yml
  tags:
    - service
