---

- name: NEWRELIC | Ensure install path
  file:
    path: "{{ newrelic_path }}"
    state: directory

- name: NEWRELIC | Check if newrelic is installed
  stat:
    path: "{{ newrelic_path }}/newrelic.jar"
  register: newrelic_jar_exists

- name: NEWRELIC | Download & Extract agent
  unarchive:
    src: "{{ newrelic_java_agent_url }}"
    remote_src: yes
    dest: "{{ newrelic_base_path }}/"
    owner: "{{ newrelic_user }}"
    group: "{{ newrelic_group }}"
  when: newrelic_jar_exists.stat.exists == false or newrelic_reinstall

- name: NEWRELIC | Configure the Java agent
  template:
    src: newrelic.yml.j2
    dest: "{{ newrelic_path }}/newrelic.yml"
    owner: "{{ newrelic_user }}"
    group: "{{ newrelic_group }}"
